default: &default
  adapter: postgresql
  #  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  encoding: utf8
  database: HR_PARKING_W
  username: postgres
  password: root
  host: localhost